// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AccountField: typeof import('./components/controls/AccountField.vue')['default']
    ActionButton: typeof import('./components/controls/ActionButton.vue')['default']
    BladeConnect: typeof import('./views/BladeConnect.vue')['default']
    BladeProvider: typeof import('./views/BladeProvider.vue')['default']
    ButtonOutlined: typeof import('./components/controls/ButtonOutlined.vue')['default']
    CircleButton: typeof import('./components/controls/CircleButton.vue')['default']
    ContractParameters: typeof import('./components/controls/ContractParameters.vue')['default']
    Field: typeof import('./components/display/Field.vue')['default']
    FormAccountInfo: typeof import('./components/forms/FormAccountInfo.vue')['default']
    FormCallContract: typeof import('./components/forms/FormCallContract.vue')['default']
    FormGetReceipt: typeof import('./components/forms/FormGetReceipt.vue')['default']
    FormSendHbar: typeof import('./components/forms/FormSendHbar.vue')['default']
    FunctionParameter: typeof import('./components/controls/FunctionParameter.vue')['default']
    NetworkInformation: typeof import('./components/display/NetworkInformation.vue')['default']
    ResultMessage: typeof import('./components/display/ResultMessage.vue')['default']
    SpinnerSmall: typeof import('./components/static/SpinnerSmall.vue')['default']
    SubmitButton: typeof import('./components/controls/SubmitButton.vue')['default']
    TextBox: typeof import('./components/controls/TextBox.vue')['default']
    TokenAmountBox: typeof import('./components/controls/TokenAmountBox.vue')['default']
    VueForm: typeof import('./components/display/VueForm.vue')['default']
    VueSection: typeof import('./components/display/VueSection.vue')['default']
    WalletAccount: typeof import('./components/display/WalletAccount.vue')['default']
    WalletBalance: typeof import('./components/display/WalletBalance.vue')['default']
  }
}

export { }
