name: build & deploy demo app

on:
  push:
    branches:
        - '**'
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLIC_HOST_BASE: wallet-demo
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '18.14.1'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - run: npm run build
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          branch: wallet-demo
          folder: dist
