name: build & deploy demo app

on:
  push:
    branches:
        - '**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.x.x
        run_install: true
    - run: pnpm i
    - run: pnpm build
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
          branch: wallet-demo
          folder: dist
